# Remember to check the `override` file

include:
  # Frontend
  - path: frontend/docker-compose.yml
    project_directory: frontend/

  # API Gateway
  - path: api_gateway/docker-compose.yml
    project_directory: api_gateway/

  # Frontend Superuser
  - path: mu_fe_superuser/docker-compose.yml
    project_directory: mu_fe_superuser/

services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs/certificado.crt:/etc/nginx/certs/certificado.crt:ro
      - ./nginx/certs/clave.key:/etc/nginx/certs/clave.key:ro
