# Remember to check the `override` file

include:
  # Frontend
  - path: frontend/docker-compose.yml
    project_directory: frontend/

  # API Gateway
  - path: api_gateway/docker-compose.yml
    project_directory: api_gateway/

  # Frontend Superuser
  - path: mu_fe_superuser/docker-compose.yml
    project_directory: mu_fe_superuser/

services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mu_fe